### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ImaCrea** [Treast/kirby-debugbar#5]
Hello there !

This plugin looks great and I'd love to use it. Though when I install it with composer, then my website is blank. body is empty, nothing seems to work :/ And this by just installing through composer. Without adding the snippet in the footer even.

Not sure where to look to find some clues as I'm pretty new with kirby and all but if you tell me where to have a look I can do some investigation and tell you.

cheers

**Comment by Treast** [comment]
Hello,

Can you try to activate the debug mode and see if there is any error ? 
https://getkirby.com/docs/guide/troubleshooting/debugging

**Comment by ImaCrea** [comment]
Hi ! Thanks for your quick reply :)

It's already activated. But all I get is this :
<img width="666" alt="Capture d’écran 2023-06-06 à 11 29 31" src="https://github.com/Treast/kirby-debugbar/assets/764332/49f0c9ea-7867-48fd-9f73-e6eadb5cd3d4">

For any page.

**Comment by Treast** [comment]
And you had something before installing the plugin ? Seems weird 

May you create a repo with your project ?

**Comment by ImaCrea** [comment]
Yes I agree it's weird. Yes I have a website fully working. The second I remove the plugin it all comes back. 🤔 

The project is not fully ready yet to publish it to a public repo I'm afraid.

**Comment by Treast** [comment]
Please check the requirements : 
- PHP 8.0 or newer
- Kirby3 (4 is untested)

If you installed it again, does the folder `site/plugins/debugbar/` exist ? Is there files inside ?

**Comment by ImaCrea** [comment]
I'm on PHP 8.2 and Kirby 3.9.
Yes the folder appears correctly and it seems to be installed.

Other plugins installed : `fabianmichael/kirby-meta` and `sylvainjule/embed`

I'm working from the Plainkit.

**Comment by Treast** [comment]
Ok, I got it. It was a problem with a library used by the package creating a conflict with KirbyCMS.

In order to fix this error, change your `index.php` file at the root to : 
```php
<?php

define('KIRBY_HELPER_DUMP', false);

require __DIR__ . '/kirby/bootstrap.php';

echo (new Kirby)->render();
```

Then it should be fine 😄

**Comment by ImaCrea** [comment]
Yay it's better, thanks !

But.. I can't see the debugbar for some reasons 🤔 I open another ticket for that ^^'
