### ISSUE TITLE
Can't see any bar at the bottom of the website

### ISSUE THREAD

**Issue by ImaCrea** [Treast/kirby-debugbar#6]
Hi,

I've followed the readme and it seems the debug bar is loaded as I can see this in the bottom of my html :

![Capture d’écran 2023-06-06 à 13 46 18](https://github.com/Treast/kirby-debugbar/assets/764332/406d6b83-357b-4dd9-80a0-1f63e3d94119)

But I don't see anything at the bottom. 

I caught a few errors in the debug console of the browser :
![Capture d’écran 2023-06-06 à 13 47 48](https://github.com/Treast/kirby-debugbar/assets/764332/3858a037-a1c4-4f64-8f0a-9f3ede724c65)
![Capture d’écran 2023-06-06 à 13 47 38](https://github.com/Treast/kirby-debugbar/assets/764332/ee246f55-409d-4056-a001-65a554688bc7)
![Capture d’écran 2023-06-06 à 13 47 30](https://github.com/Treast/kirby-debugbar/assets/764332/ea168f03-c6d9-4e65-ab93-898b5203c1f9)

**Comment by Treast** [comment]
Should be fixed with  02e24c8695119985f2e3dc486a2c82f22ed3f7c6

I just release a new version (1.3.1), so you just have to run a `composer update`. Let me know if everything is okay

**Comment by ImaCrea** [comment]
Hey, I was just on it and found out it works if load jquery first in the footer `<script src=" https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js "></script>`.

Gonna try to update and I tell you :)

**Comment by ImaCrea** [comment]
Did the update and it's working perfectly! Thank you 🙏 🤗 

(btw no need to load jquery in the footer anymore ofc)

**Comment by Treast** [comment]
Yeah the fix sould work then. The regex on the `.gitignore` also removed the `assets/vendor` folder.
