### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [Treast/kirby-debugbar#7]
> The internal $model->contentFiles() method has been deprecated. You can use $model->storage()->contentFiles() instead, however please note that this method is also internal and may be removed in the future.

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by Treast** [comment]
Should be fixed on v1.3.2.

I've only checked on the starter kit v4, tell me if it's good for you !

**Comment by afbora** [comment]
Works great, thanks!

**Comment by afbora** [comment]
Updated K4 compatibility in getkirby.com plugins directory https://github.com/getkirby/getkirby.com/commit/4588df551952339a5939214088a88b0b0e45d4bf
